services:
  - type: web
    name: my-laravel-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: MyPortfolio
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://my-myportfolio-project.onrender.com
      - key: APP_KEY
        generateValue: true

      # Session & Cache
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: SESSION_ENCRYPT
        value: false
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: database

      # Mail Settings
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: yammar673@gmail.com
      - key: MAIL_PASSWORD
        value: gdzfrsxuiyzirphg
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: your@gmail.com
      - key: MAIL_FROM_NAME
        value: MyPortfolio

      # Database Settings (Adjust according to your DB on Render)
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: myportfolio
      - key: DB_USERNAME
        value: your-db-user
      - key: DB_PASSWORD
        value: your-db-password
